### ISSUE TITLE
target-selector attribute in brick-tabbar gone?

### ISSUE THREAD

**Issue by sole** [mozbrick/brick-tabbar#16]
Porting existing code from x-tag based tabbar. It appears that I can't use the `target-selector` attribute anymore and I now need to use an specific id instead of a selector?

Are there plans to bring back this functionality?

**Comment by dotch** [comment]
we switched to only using ids in all our component selectors.
this is open for discussion as long as we do it consistently across all components!

**Comment by potch** [comment]
There aren't plans, but there could be plans! The idea of selectors (which can return more than one element) isn't really DOMy, and encourages things like `target-selector='element:nth-child(5):not(.thatone)'` which is pretty un-nice.

**Comment by sole** [comment]
Right, I see! I don't have a strong opinion on this to be honest. It might be even better to be simpler in that sense.
I'll change the template code to use plain `id`s.

**Comment by potch** [comment]
Alright- strong 'meh' all around! :fireworks:
