### ISSUE TITLE
tabs parameter doesn't exist

### ISSUE THREAD

**Issue by zalun** [mozbrick/brick-tabbar#28]
After implementing the tabbar with deck I wanted to iterate by tabs to link them back with cards.
- https://github.com/zalun/school-plan-app/blob/master/stage4/index.html#L34
- https://github.com/zalun/school-plan-app/blob/master/stage4/js/index.js#L19

TypeError: app.planGroupMenu.tabs is undefined

**Comment by zalun** [comment]
It's the race condition issue.
Polyfill upgrading process wasn't finished
It's there after waiting for a while - `window.setTimeout(tabsCheck, 100)`
In the project I decided to wait for the ``tabs` parameter
https://github.com/zalun/school-plan-app/blob/master/stage4/js/index.js#L20

**Comment by kentaromiura** [comment]
This is a known 'issue', it's related to the upgrading process of the custom element polyfill,
it happens to all the custom element already present on the page while the page load, at that point the browser has no knowledge of those so it use HTMLUnknown to render them before the polyfill promotes them asynchronously.

You appear to try to access a getter before the polyfill had the chance of promoting it.

The google polyfill fires a WebComponentsReady event once all those element have been upgraded.
This is not standard though and you shouldn't be using it as they could remove it later, a fine solution is polling to ensure that the property / method exists before accessing / using it.
